<?php

namespace Database\Seeders;

use App\Models\Course;
use Illuminate\Database\Seeder;

class CourseTableSeeder extends Seeder
{
    /**
     * Run the database seeds.
     *
     * @return void
     */
    public function run(): void
    {
        $this->createDefaultCourses();
    }

    public function createDefaultCourses (): void {
        $courses = [
            ['shortcut' => 'IJA', 'name' => 'Seminář Java', 'capacity' => 500, 'price' => 1000, 'guarantorID' => 6, 'is_confirmed' => 1, 'created_at' => now(), 'updated_at' => now(), 'description' => 'Lorem ipsum dolor sit amet, consectetuer adipiscing elit. Aenean fermentum risus id tortor. Donec vitae arcu. Nullam rhoncus aliquam metus. Duis aute irure dolor in reprehenderit in voluptate velit esse cillum dolore eu fugiat nulla pariatur. Fusce tellus odio, dapibus id fermentum quis, suscipit id erat. Maecenas libero. Nam quis nulla. Sed ut perspiciatis unde omnis iste natus error sit voluptatem accusantium doloremque laudantium, totam rem aperiam, eaque ipsa quae ab illo inventore veritatis et quasi architecto beatae vitae dicta sunt explicabo.', 'date_from'=>'2022-09-01 00:00:00', 'date_to'=>'2022-12-12 00:00:00'],
            ['shortcut' => 'ITU', 'name' => 'Tvorba uživatelských rozhraní', 'capacity' => 400, 'price' => 2000, 'guarantorID' => 6, 'is_confirmed' => 1, 'created_at' => now(), 'updated_at' => now(), 'description' => 'Lorem ipsum dolor sit amet, consectetuer adipiscing elit. Aenean fermentum risus id tortor. Donec vitae arcu. Nullam rhoncus aliquam metus. Duis aute irure dolor in reprehenderit in voluptate velit esse cillum dolore eu fugiat nulla pariatur. Fusce tellus odio, dapibus id fermentum quis, suscipit id erat. Maecenas libero. Nam quis nulla. Sed ut perspiciatis unde omnis iste natus error sit voluptatem accusantium doloremque laudantium, totam rem aperiam, eaque ipsa quae ab illo inventore veritatis et quasi architecto beatae vitae dicta sunt explicabo.', 'date_from'=>'2022-09-01 00:00:00', 'date_to'=>'2022-12-12 00:00:00'],
            ['shortcut' => 'IIS', 'name' => 'Informační systémy', 'capacity' => 300, 'price' => 3000, 'guarantorID' => 7, 'is_confirmed' => 1, 'created_at' => now(), 'updated_at' => now(), 'description' => 'Lorem ipsum dolor sit amet, consectetuer adipiscing elit. Aenean fermentum risus id tortor. Donec vitae arcu. Nullam rhoncus aliquam metus. Duis aute irure dolor in reprehenderit in voluptate velit esse cillum dolore eu fugiat nulla pariatur. Fusce tellus odio, dapibus id fermentum quis, suscipit id erat. Maecenas libero. Nam quis nulla. Sed ut perspiciatis unde omnis iste natus error sit voluptatem accusantium doloremque laudantium, totam rem aperiam, eaque ipsa quae ab illo inventore veritatis et quasi architecto beatae vitae dicta sunt explicabo.', 'date_from'=>'2022-09-01 00:00:00', 'date_to'=>'2022-12-12 00:00:00'],
            ['shortcut' => 'ISS', 'name' => 'Signály a systémy', 'capacity' => 200, 'price' => 4000, 'guarantorID' => 7, 'is_confirmed' => 1, 'created_at' => now(), 'updated_at' => now(), 'description' => 'Lorem ipsum dolor sit amet, consectetuer adipiscing elit. Aenean fermentum risus id tortor. Donec vitae arcu. Nullam rhoncus aliquam metus. Duis aute irure dolor in reprehenderit in voluptate velit esse cillum dolore eu fugiat nulla pariatur. Fusce tellus odio, dapibus id fermentum quis, suscipit id erat. Maecenas libero. Nam quis nulla. Sed ut perspiciatis unde omnis iste natus error sit voluptatem accusantium doloremque laudantium, totam rem aperiam, eaque ipsa quae ab illo inventore veritatis et quasi architecto beatae vitae dicta sunt explicabo.', 'date_from'=>'2022-09-01 00:00:00', 'date_to'=>'2022-12-12 00:00:00'],
            ['shortcut' => 'IJC', 'name' => 'Jazyk C', 'capacity' => 500, 'price' => 1000, 'guarantorID' => 8, 'is_confirmed' => 1, 'created_at' => now(), 'updated_at' => now(), 'description' => 'Lorem ipsum dolor sit amet, consectetuer adipiscing elit. Aenean fermentum risus id tortor. Donec vitae arcu. Nullam rhoncus aliquam metus. Duis aute irure dolor in reprehenderit in voluptate velit esse cillum dolore eu fugiat nulla pariatur. Fusce tellus odio, dapibus id fermentum quis, suscipit id erat. Maecenas libero. Nam quis nulla. Sed ut perspiciatis unde omnis iste natus error sit voluptatem accusantium doloremque laudantium, totam rem aperiam, eaque ipsa quae ab illo inventore veritatis et quasi architecto beatae vitae dicta sunt explicabo.', 'date_from'=>'2022-09-01 00:00:00', 'date_to'=>'2022-12-12 00:00:00'],
            ['shortcut' => 'IZP', 'name' => 'Základy programování', 'capacity' => 400, 'price' => 2000, 'guarantorID' => 8, 'is_confirmed' => 1, 'created_at' => now(), 'updated_at' => now(), 'description' => 'Lorem ipsum dolor sit amet, consectetuer adipiscing elit. Aenean fermentum risus id tortor. Donec vitae arcu. Nullam rhoncus aliquam metus. Duis aute irure dolor in reprehenderit in voluptate velit esse cillum dolore eu fugiat nulla pariatur. Fusce tellus odio, dapibus id fermentum quis, suscipit id erat. Maecenas libero. Nam quis nulla. Sed ut perspiciatis unde omnis iste natus error sit voluptatem accusantium doloremque laudantium, totam rem aperiam, eaque ipsa quae ab illo inventore veritatis et quasi architecto beatae vitae dicta sunt explicabo.', 'date_from'=>'2022-09-01 00:00:00', 'date_to'=>'2022-12-12 00:00:00'],
            ['shortcut' => 'INP', 'name' => 'Návrh počítačových systémů', 'capacity' => 300, 'price' => 3000, 'guarantorID' => 9, 'is_confirmed' => 1, 'created_at' => now(), 'updated_at' => now(), 'description' => 'Lorem ipsum dolor sit amet, consectetuer adipiscing elit. Aenean fermentum risus id tortor. Donec vitae arcu. Nullam rhoncus aliquam metus. Duis aute irure dolor in reprehenderit in voluptate velit esse cillum dolore eu fugiat nulla pariatur. Fusce tellus odio, dapibus id fermentum quis, suscipit id erat. Maecenas libero. Nam quis nulla. Sed ut perspiciatis unde omnis iste natus error sit voluptatem accusantium doloremque laudantium, totam rem aperiam, eaque ipsa quae ab illo inventore veritatis et quasi architecto beatae vitae dicta sunt explicabo.', 'date_from'=>'2022-09-01 00:00:00', 'date_to'=>'2022-12-12 00:00:00'],
            ['shortcut' => 'INC', 'name' => 'Návrh číslicových systémů', 'capacity' => 200, 'price' => 4000, 'guarantorID' => 9, 'is_confirmed' => 1, 'created_at' => now(), 'updated_at' => now(), 'description' => 'Lorem ipsum dolor sit amet, consectetuer adipiscing elit. Aenean fermentum risus id tortor. Donec vitae arcu. Nullam rhoncus aliquam metus. Duis aute irure dolor in reprehenderit in voluptate velit esse cillum dolore eu fugiat nulla pariatur. Fusce tellus odio, dapibus id fermentum quis, suscipit id erat. Maecenas libero. Nam quis nulla. Sed ut perspiciatis unde omnis iste natus error sit voluptatem accusantium doloremque laudantium, totam rem aperiam, eaque ipsa quae ab illo inventore veritatis et quasi architecto beatae vitae dicta sunt explicabo.', 'date_from'=>'2022-09-01 00:00:00', 'date_to'=>'2022-12-12 00:00:00'],
            ['shortcut' => 'IEL', 'name' => 'Elektronika pro informační technologie', 'capacity' => 500, 'price' => 1000, 'guarantorID' => 6, 'is_confirmed' => 1, 'created_at' => now(), 'updated_at' => now(), 'description' => 'Lorem ipsum dolor sit amet, consectetuer adipiscing elit. Aenean fermentum risus id tortor. Donec vitae arcu. Nullam rhoncus aliquam metus. Duis aute irure dolor in reprehenderit in voluptate velit esse cillum dolore eu fugiat nulla pariatur. Fusce tellus odio, dapibus id fermentum quis, suscipit id erat. Maecenas libero. Nam quis nulla. Sed ut perspiciatis unde omnis iste natus error sit voluptatem accusantium doloremque laudantium, totam rem aperiam, eaque ipsa quae ab illo inventore veritatis et quasi architecto beatae vitae dicta sunt explicabo.', 'date_from'=>'2022-09-01 00:00:00', 'date_to'=>'2022-12-12 00:00:00'],
            ['shortcut' => 'IAL', 'name' => 'Algoritmy', 'capacity' => 400, 'price' => 2000, 'guarantorID' => 6, 'is_confirmed' => 1, 'created_at' => now(), 'updated_at' => now(), 'description' => 'Lorem ipsum dolor sit amet, consectetuer adipiscing elit. Aenean fermentum risus id tortor. Donec vitae arcu. Nullam rhoncus aliquam metus. Duis aute irure dolor in reprehenderit in voluptate velit esse cillum dolore eu fugiat nulla pariatur. Fusce tellus odio, dapibus id fermentum quis, suscipit id erat. Maecenas libero. Nam quis nulla. Sed ut perspiciatis unde omnis iste natus error sit voluptatem accusantium doloremque laudantium, totam rem aperiam, eaque ipsa quae ab illo inventore veritatis et quasi architecto beatae vitae dicta sunt explicabo.', 'date_from'=>'2022-09-01 00:00:00', 'date_to'=>'2022-12-12 00:00:00'],
            ['shortcut' => 'ISA', 'name' => 'Síťové aplikace a správa sítí', 'capacity' => 300, 'price' => 3000, 'guarantorID' => 7, 'is_confirmed' => 1, 'created_at' => now(), 'updated_at' => now(), 'description' => 'Lorem ipsum dolor sit amet, consectetuer adipiscing elit. Aenean fermentum risus id tortor. Donec vitae arcu. Nullam rhoncus aliquam metus. Duis aute irure dolor in reprehenderit in voluptate velit esse cillum dolore eu fugiat nulla pariatur. Fusce tellus odio, dapibus id fermentum quis, suscipit id erat. Maecenas libero. Nam quis nulla. Sed ut perspiciatis unde omnis iste natus error sit voluptatem accusantium doloremque laudantium, totam rem aperiam, eaque ipsa quae ab illo inventore veritatis et quasi architecto beatae vitae dicta sunt explicabo.', 'date_from'=>'2022-09-01 00:00:00', 'date_to'=>'2022-12-12 00:00:00'],
            ['shortcut' => 'ISU', 'name' => 'Programování na strojové úrovni', 'capacity' => 200, 'price' => 4000, 'guarantorID' => 7, 'is_confirmed' => 1, 'created_at' => now(), 'updated_at' => now(), 'description' => 'Lorem ipsum dolor sit amet, consectetuer adipiscing elit. Aenean fermentum risus id tortor. Donec vitae arcu. Nullam rhoncus aliquam metus. Duis aute irure dolor in reprehenderit in voluptate velit esse cillum dolore eu fugiat nulla pariatur. Fusce tellus odio, dapibus id fermentum quis, suscipit id erat. Maecenas libero. Nam quis nulla. Sed ut perspiciatis unde omnis iste natus error sit voluptatem accusantium doloremque laudantium, totam rem aperiam, eaque ipsa quae ab illo inventore veritatis et quasi architecto beatae vitae dicta sunt explicabo.', 'date_from'=>'2022-09-01 00:00:00', 'date_to'=>'2022-12-12 00:00:00'],
            ['shortcut' => 'IUS', 'name' => 'Úvod do softwarového inženýrství', 'capacity' => 500, 'price' => 1000, 'guarantorID' => 8, 'is_confirmed' => 1, 'created_at' => now(), 'updated_at' => now(), 'description' => 'Lorem ipsum dolor sit amet, consectetuer adipiscing elit. Aenean fermentum risus id tortor. Donec vitae arcu. Nullam rhoncus aliquam metus. Duis aute irure dolor in reprehenderit in voluptate velit esse cillum dolore eu fugiat nulla pariatur. Fusce tellus odio, dapibus id fermentum quis, suscipit id erat. Maecenas libero. Nam quis nulla. Sed ut perspiciatis unde omnis iste natus error sit voluptatem accusantium doloremque laudantium, totam rem aperiam, eaque ipsa quae ab illo inventore veritatis et quasi architecto beatae vitae dicta sunt explicabo.', 'date_from'=>'2022-09-01 00:00:00', 'date_to'=>'2022-12-12 00:00:00'],
            ['shortcut' => 'IPT', 'name' => 'Pravděpodobnost a statistika', 'capacity' => 400, 'price' => 2000, 'guarantorID' => 8, 'is_confirmed' => 1, 'created_at' => now(), 'updated_at' => now(), 'description' => 'Lorem ipsum dolor sit amet, consectetuer adipiscing elit. Aenean fermentum risus id tortor. Donec vitae arcu. Nullam rhoncus aliquam metus. Duis aute irure dolor in reprehenderit in voluptate velit esse cillum dolore eu fugiat nulla pariatur. Fusce tellus odio, dapibus id fermentum quis, suscipit id erat. Maecenas libero. Nam quis nulla. Sed ut perspiciatis unde omnis iste natus error sit voluptatem accusantium doloremque laudantium, totam rem aperiam, eaque ipsa quae ab illo inventore veritatis et quasi architecto beatae vitae dicta sunt explicabo.', 'date_from'=>'2022-09-01 00:00:00', 'date_to'=>'2022-12-12 00:00:00'],
            ['shortcut' => 'IMA1', 'name' => 'Matematická analýza 1', 'capacity' => 300, 'price' => 3000, 'guarantorID' => 9, 'is_confirmed' => 1, 'created_at' => now(), 'updated_at' => now(), 'description' => 'Lorem ipsum dolor sit amet, consectetuer adipiscing elit. Aenean fermentum risus id tortor. Donec vitae arcu. Nullam rhoncus aliquam metus. Duis aute irure dolor in reprehenderit in voluptate velit esse cillum dolore eu fugiat nulla pariatur. Fusce tellus odio, dapibus id fermentum quis, suscipit id erat. Maecenas libero. Nam quis nulla. Sed ut perspiciatis unde omnis iste natus error sit voluptatem accusantium doloremque laudantium, totam rem aperiam, eaque ipsa quae ab illo inventore veritatis et quasi architecto beatae vitae dicta sunt explicabo.', 'date_from'=>'2022-09-01 00:00:00', 'date_to'=>'2022-12-12 00:00:00'],
            ['shortcut' => 'IMA2', 'name' => 'Matematikcá analýza 2', 'capacity' => 200, 'price' => 4000, 'guarantorID' => 9, 'is_confirmed' => 1, 'created_at' => now(), 'updated_at' => now(), 'description' => 'Lorem ipsum dolor sit amet, consectetuer adipiscing elit. Aenean fermentum risus id tortor. Donec vitae arcu. Nullam rhoncus aliquam metus. Duis aute irure dolor in reprehenderit in voluptate velit esse cillum dolore eu fugiat nulla pariatur. Fusce tellus odio, dapibus id fermentum quis, suscipit id erat. Maecenas libero. Nam quis nulla. Sed ut perspiciatis unde omnis iste natus error sit voluptatem accusantium doloremque laudantium, totam rem aperiam, eaque ipsa quae ab illo inventore veritatis et quasi architecto beatae vitae dicta sunt explicabo.', 'date_from'=>'2022-09-01 00:00:00', 'date_to'=>'2022-12-12 00:00:00']
        ];

        Course::insert($courses);
    }
}
